name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt test

